name: Build accent_color plugin

on:
  workflow_dispatch:
  push:
    branches:
      - Plugins
    paths:
      - ".github/workflows/build-plugin-accent-color.yml"
      - ".github/workflows/build-plugins.yml"
      - "PluginCatalog/CMakeLists.txt"
      - "PluginCatalog/accent_color/**"
      - "Telegram/Plugins/Examples/accent_color.cpp"
      - "Telegram/SourceFiles/plugins/**"
      - "Telegram/SourceFiles/settings/settings_plugins.cpp"
      - "Telegram/build/prepare/prepare.py"
      - "Telegram/build/prepare/win.bat"
      - "Telegram/build/qt_version.py"

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip plugin-catalog]') }}
    uses: ./.github/workflows/build-plugins.yml
    with:
      plugin_name: accent_color
      allow_commit: ${{ github.event_name == 'push' }}
      target_branch: Plugins
    secrets: inherit
