name: Build font_tuner plugin

on:
  workflow_dispatch:
  push:
    branches:
      - Plugins
    paths:
      - ".github/workflows/build-plugin-font-tuner.yml"
      - ".github/workflows/build-plugin-reusable.yml"
      - "PluginCatalog/CMakeLists.txt"
      - "PluginCatalog/font_tuner/**"
      - "Telegram/Plugins/Examples/font_tuner.cpp"
      - "Telegram/SourceFiles/plugins/**"
      - "Telegram/SourceFiles/settings/settings_plugins.cpp"
      - "Telegram/build/prepare/prepare.py"
      - "Telegram/build/prepare/win.bat"
      - "Telegram/build/qt_version.py"

permissions:
  contents: write

concurrency:
  group: build-plugin-font-tuner-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip plugin-build]') }}
    uses: ./.github/workflows/build-plugin-reusable.yml
    with:
      plugin_name: font_tuner
      allow_commit: ${{ github.event_name == 'push' }}
      target_branch: Plugins
    secrets: inherit
