name: Build show_logs plugin

on:
  workflow_dispatch:
  push:
    branches:
      - Plugins
    paths:
      - ".github/workflows/build-plugin-show-logs.yml"
      - ".github/workflows/build-plugin-reusable.yml"
      - "PluginCatalog/CMakeLists.txt"
      - "PluginCatalog/show_logs/**"
      - "Telegram/Plugins/Examples/show_logs.cpp"
      - "Telegram/SourceFiles/plugins/**"
      - "Telegram/SourceFiles/settings/settings_plugins.cpp"
      - "Telegram/build/prepare/prepare.py"
      - "Telegram/build/prepare/win.bat"
      - "Telegram/build/qt_version.py"

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip plugin-build]') }}
    uses: ./.github/workflows/build-plugin-reusable.yml
    with:
      plugin_name: show_logs
      allow_commit: ${{ github.event_name == 'push' }}
      target_branch: Plugins
    secrets: inherit
